### ISSUE TITLE
Joystick deadzone too low

### ISSUE THREAD

**Issue by strycore** [solarus-games/solarus#672]
I tried playing the game with a joypad (xbox 360 controller) and most of the time, Link will continue moving even when not interacting with the joystick. This often happen in games where the deadzone value is set too low. 
SDL axis values go from 0 to 32768, a common deadzone value is 8000. I tried looking at the source code (without going too much into details) and I saw that axis values where ignored under 10000. If the deadzone value really is 10000 then that's kinda weird and this bug shouldn't happen.

**Comment by strycore** [comment]
After further inspection, this doesn't seem to be a deadzone issue but seems to be related to the ways input axis are handled in the current code. This issue is not present in Solarus 1.3 and I replaced the current code with a more straightforward one (taken from http://lazyfoo.net/tutorials/SDL/19_gamepads_and_joysticks/index.php) and the issue disappeared as well (but introduced other issues in the inventory screen)

**Comment by christopho** [comment]
Do you have a patch?
If you are able to fix it and keep the inventory screen okay, I will be happy to accept a pull request.
Thanks for you contribution

**Comment by christopho** [comment]
It is weird if you have the issue in the development version but not in 1.3, because I don't think anything has changed in the joystick handling code since 1.3.

**Comment by strycore** [comment]
I'll try to write a patch when I get back to this issue, I'll also try building the 1.3 version to see what's wrong with this piece of code. Maybe it isn't a problem with the code but with how it's built.

**Comment by christopho** [comment]
https://github.com/christopho/solarus/commit/f171441185394a3ced09fac8e7724b34d903189c fixes problems with the hero of the inventory cursor not always correctly responding to directions. Maybe it improves your situation?

**Comment by christopho** [comment]
I am assuming the problem is fixed in 1.4, by commit f171441. Please reopen if this is not the case.

**Comment by Diarandor** [comment]
Hi! I am having this problem with the development version of Solarus 1.5. I use a xbox 360 controller too. I think there was no bug in the version 1.4.5, if my memory is not wrong.

**Comment by christopho** [comment]
Reopening as asked by @Diarandor.

**Comment by Diarandor** [comment]
I still have this problem while using an Xbox360 controller. The hero does not stop walking sometimes. For the left and right directions, it happens 50% of the times, aproximately. (However, I do not have problems for the up and down directions.)
I think I did not have this problem in the 1.4.5 version but I am not completely sure since I cannot remember it now.

**Comment by christopho** [comment]
@strycore If you can't make a patch, could you explain how you fixed this issue? This would help a lot because I don't reproduce it. Thanks in advance

**Comment by strycore** [comment]
I'd like to get back to this issue but I'm currently having some problems running the game in the first place. I made this script to build the game: https://github.com/lutris/buildbot/blob/master/games/solarus/build.sh and the game runs fine in the menu,  but when starting the actual game I get the following error: 

```
Error: Failed to load map: [string "maps/0.dat"]:1: bad argument #1 to properties (Bad field 'num_layers' (integer expected, got nil))
Fatal: Failed to load map data file 'maps/0.dat'
```

Is there something I'm doing wrong in my script? 

I should also have a look on my previous computer were I actually got the game running and wrote the patch.

**Comment by strycore** [comment]
Ok, I found my previous build of solarus, if I can ever the the current game running I'll integrate it and make a proper pull request. Meanwhile, I'm attaching it as a patch to this issue.
[input.patch.txt](https://github.com/christopho/solarus/files/178851/input.patch.txt)

**Comment by christopho** [comment]
To fix the build, use branch dev (of both solarus and zsdx) instead of master. dev is now the default branch of all our repositories.
Or if you want the latest release rather than the development version, use solarus with the tag v1.4.5 and zsdx with the tag zsdx-1.10.3.
(The branch master is currently in an intermediate state, sorry about that. Starting with the 1.5 release, it will always point to the latest release.)

Anyway thanks for the patch!

**Comment by frostigmeister** [comment]
Still have this problem. Xbox 360 controller, solarus 1.5.2, zsdx 1.11.0. 

It appears that there is some kind of angle I must not release the D-Pad. If I move it to the edge and release it the character stops, same if I only move it a small bit and then release it.

**Comment by CipherpunkChris** [comment]
I'm still experiencing this issue with an Xbox One wireless controller. I just downloaded the latest version of Solarus, 1.5.3.

**Comment by ghost** [comment]
"still experiencing this issue with an Xbox One wireless controller. I just downloaded the latest version of Solarus, 1.5.3."

Can confirm this on linux, fedora and solus tested.
